export default {
  ACCEPT_REQUEST: 'ACCEPT_REQUEST',
  AUTHENTICATE: 'AUTHENTICATE',
  BLACKLIST: 'BLACKLIST',
  GENERATE_NEW_HANDSHAKE_NODE: 'GENERATE_NEW_HANDSHAKE_NODE',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  SEND_HANDSHAKE_REQUEST: 'SEND_HANDSHAKE_REQUEST',
  SEND_HANDSHAKE_REQUEST_WITH_INITIAL_MSG: "SEND_HANDSHAKE_REQUEST_WITH_INITIAL_MSG",
  SEND_MESSAGE: 'SEND_MESSAGE',
  SET_AVATAR: 'SET_AVATAR',
  SET_DISPLAY_NAME: 'SET_DISPLAY_NAME',
}